image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\proj

cache:		
  - c:\projects\build1\vcpkg\scripts -> appveyor.yml		
  - c:\projects\build1\vcpkg\installed -> appveyor.yml
 
platform:
- x86

install:  
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd "C:\Program Files (x86)"
  - rd /s /q CMake
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-rc4-win32-x86.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip		
  - 7z x cmake.zip -oC:\projects\deps > nul		
  - cd "C:\Program Files (x86)"
  - move C:\projects\deps\cmake-* cmake
  - cmake --version
  - cd c:\projects
  - IF NOT EXIST c:\projects\build1 mkdir build1
  - cd build1
  - IF NOT EXIST c:\projects\build1\vcpkg git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - IF NOT EXIST c:\projects\build1\vcpkg\installed\x86-windows powershell -exec bypass scripts\bootstrap.ps1
  - IF NOT EXIST c:\projects\build1\vcpkg\installed\x86-windows .\vcpkg install fltk libjpeg-turbo zlib openssl boost libuv
  - cd c:\projects\proj
  - mkdir build
  - cd build
  - cmake "-DCMAKE_TOOLCHAIN_FILE=c:\projects\build1\vcpkg\scripts\buildsystems\vcpkg.cmake" .. 
  
build_script:
  - cmake --build .
