
image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\rat

platform:
- x86
- x64     

environment:
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  OPENSSL_ROOT_DIR: C:\OpenSSL-Win32
  
install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  
before_build:
  - echo Running cmake...
  - cd c:\projects\rat
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install fltk:%PLATFORM%-windows-static libjpeg-turbo:%PLATFORM%-windows-static zlib:%PLATFORM%-windows-static
  - cd ..
  - cmake .. "-DCMAKE_TOOLCHAIN_FILE=c:\projects\rat\build\vcpkg\scripts\buildsystems\vcpkg.cmake"

build:
  verbosity: detailed
  project: rat.sln 
