
image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\rat

platform:
- x86
- x64        
        
install:
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-rc3-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  
before_build:
  - echo Running cmake...
  - cd c:\projects\rat
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install fltk:%PLATFORM%-windows-static libjpeg-turbo:%PLATFORM%-windows-static zlib:%PLATFORM%-windows-static
  - cd ..
  - cmake -DCMAKE_TOOLCHAIN_FILE=build\vcpkg\scripts\buildsystems\vcpkg.cmake -DOPENSSL_ROOT_DIR=C:\OpenSSL-Win32 -DBOOST_ROOT=C:\Libraries\boost_1_63_0 ..
  
build:
  verbosity: detailed
  project: rat.sln 
