
image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\rat

before_build:
  - echo Running cmake...
  - cd c:\projects\rat
  - mkdir build
  - cd build
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install fltk libjpeg-turbo zlib
  - cd ..
  - cmake  .. "-DCMAKE_TOOLCHAIN_FILE=build\vcpkg\scripts\buildsystems\vcpkg.cmake"
  
build:
  verbosity: detailed
  project: rat.sln 
