language : cpp

matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew outdated boost || brew upgrade boost && brew install fltk openssl libjpeg-turbo;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -y libfltk1.3-dev;
    fi  
    
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ . && make;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       cmake . && make;
    fi  
