language : cpp

matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      addons:
        apt:
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libssl-dev
      
before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
     mkdir $HOME/usr && export PATH="$HOME/usr/bin:$PATH" && wget https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh && chmod +x cmake-3.7.2-Linux-x86_64.sh && ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew outdated boost || brew upgrade boost && brew install fltk openssl libjpeg-turbo && brew upgrade cmake || brew install cmake;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -y libjpeg-turbo8-dev libboost-all-dev libfltk1.3-dev clang libxext-dev libx11-dev libxfixes-dev gcc libxtst-dev;
    fi  
    
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ . && make;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       cmake . && make;
    fi  
