language : cpp

matrix:
  include:
    - os: osx
    - os: linux
      sudo: required
      addons:
        apt:
          packages:
            - clang-3.8
            - libssl-dev
      
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew outdated boost || brew upgrade boost && brew install fltk openssl libjpeg-turbo && brew upgrade cmake || brew install cmake;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo apt-get install -y libjpeg-turbo8-dev libboost-all-dev libfltk1.3-dev clang libxext-dev libx11-dev libxfixes-dev gcc libxtst-dev;
    fi  
    
install:    
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
 
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
        mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
      fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    fi
  - cd ..    
  - cmake --version
  
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ . && make;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
       cmake -DOPENSSL_ROOT_DIR=/usr/include -DOPENSSL_LIBRARIES=/usr/lib . && make;
    fi  
