language : cpp

osx_image: xcode8.2

os:
   - osx
    
before_install:
    - brew update
    - brew outdated boost || brew upgrade boost
    - brew install fltk openssl libjpeg-turbo

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ . 
        ./configure && make;
    fi

