language : cpp

matrix:
  include:
    - os: osx
      
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update && brew outdated boost || brew upgrade boost && brew install fltk openssl libjpeg-turbo;
    fi
    
script:

